# Site settings
title: DobotCrypto-NFT 
email: wahyu243@gmail.com
description: DobotCrypto-NFT  is a Collection Dog Robot Crypto living on Polygon Blokchain. Each of them are Super without Generative Approach.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dobotcrypto.xyz" # the base hostname & protocol for your site

facebook_username: dobotcryptoclub
github_username: wahyu243/dobotcryptoclub

# Build settings
markdown: kramdown
